routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.master');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


/**
 * Backend Routes
 */

Route::group([
    'prefix' => 'intranet',
    'middleware' => 'auth'
], function () {

    Route::get('users/datatable', 'UsersController@dataTable')->name('users.datatable');
    Route::get('groups/datatable', 'GroupsController@dataTable')->name('groups.datatable');
    Route::get('members/datatable', 'MembersController@dataTable')->name('members.datatable');
    Route::get('contributions/datatable', 'ContributionsController@dataTable')->name('contributions.datatable');

    Route::resource('users', 'UsersController');
    Route::resource('members', 'MembersController');
    Route::resource('groups', 'GroupsController');
    Route::resource('contributions', 'ContributionsController');
});

app/Models/Group.php
<?php

namespace App\Models;

use Spatie\Activitylog\LogsActivity;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Spatie\Activitylog\LogsActivityInterface;
use Venturecraft\Revisionable\RevisionableTrait;

/**
 * Class Group.
 *
 * @package namespace App\Models;
 */
class Group extends Model implements  LogsActivityInterface
{
    use Sluggable, LogsActivity, RevisionableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'telephone', 'slug', 'location'
    ];

    /*
    |--------------------------------------------------------------------------
    | FUNCTIONS
    |--------------------------------------------------------------------------
    */

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    /**
     * Get the message that needs to be logged for the given event name.
     *
     * @param string $eventName
     *
     * @return string
     */
    public function getActivityDescriptionForEvent($eventName)
    {
        if ($eventName == 'created') {
            return 'Group "' . $this->name . '" was created';
        }

        if ($eventName == 'updated') {
            return 'Group "' . $this->name . '" was updated';
        }

        if ($eventName == 'deleted') {
            return 'Group "' . $this->name . '" was deleted';
        }

        return '';
    }

    public function membershipCount()
    {
        return $this->members()->count();
    }

    public function contributionSum()
    {
        return $this->contribution()->sum('amount');
    }

    /*
    |--------------------------------------------------------------------------
    | RELATIONSHIPS
    |--------------------------------------------------------------------------
    */
    public function members()
    {
        return $this->hasMany(Member::class);
    }

    /**
     *  Get the sum of each group contribution
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasManyThrough
     */
    public function contribution()
    {
        return $this->hasManyThrough(
            Contribution::class,
            Member::class,
            'group_id',
            'id');
    }

    /**
     * A group can have one contactPerson(user)
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function user()
    {
        return $this->hasMany(User::class);
    }
}

app/Http/Controllers/GroupsController.php
<?php

namespace App\Http\Controllers;

use App\Contracts\Repositories\GroupRepository;
use App\Contracts\Repositories\UserRepository;
use App\Http\Requests\GroupCreateRequest;
use App\Http\Requests\GroupUpdateRequest;
use App\Validators\GroupValidator;

/**
 * Class GroupsController.
 *
 * @package namespace App\Http\Controllers;
 */
class GroupsController extends Controller
{
    /**
     * @var GroupRepository
     */
    protected $repository;

    /**
     * @var userRepository
     */
    protected $userRepository;

    /**
     * GroupsController constructor.
     *
     * @param GroupRepository $repository
     * @param UserRepository $userRepository
     */
    public function __construct(GroupRepository $repository, UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
        $this->repository = $repository;
    }

    /**
     *  Fetch dataTable records of  resource
     * @return mixed
     */
    public function dataTable()
    {
        return $this->repository->getDataTable();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));

        $groups = $this->repository->all();

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $groups,
            ]);
        }

        return view('backend.groups.index', compact('groups'));
    }

    /**
     * Shows the form for creating a new resource
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('backend.groups.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  GroupCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     *
     *
     */
    public function store(GroupCreateRequest $request)
    {
        $user = $this->userRepository->skipPresenter()->create([
            'name'      => $request->admin_name,
            'email'     => $request->admin_email,
            'telephone' => $request->admin_telephone,
            'password'  => bcrypt(config('sacco.default-password'))
        ]);

        $group = $this->repository->create([
            'name'     => $request->name,
            'email'    => $request->email,
            'location' => $request->location,
            'user_id'  => $user->id,
        ]);

        $response = [
            'message' => 'Group created.',
//            'data'    => $group->toArray(),
        ];

        if ($request->wantsJson()) {

            return response()->json($response);
        }

        return redirect()->back()->with('message', $response['message']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $group = $this->repository->find($id);

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $group,
            ]);
        }

        return view('groups.show', compact('group'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $group = $this->repository->find($id);

        $user = $group->user;

        return view('backend.groups.edit', compact('group', 'user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  GroupUpdateRequest $request
     * @param  string $id
     *
     * @return Response
     *
     */
    public function update(GroupUpdateRequest $request, $id)
    {
        $groupResult = $this->repository->find($id);

        $userId = $groupResult->user_id;

        $group = $this->repository->update($request->all(), $id);

        $this->userRepository->update([
            'name'      => $request->admin_name,
            'email'     => $request->admin_email,
            'telephone' => $request->admin_telephone,
        ], $userId);

        $response = [
            'message' => 'Group updated.',
            'data'    => $group->toArray(),
        ];

        if ($request->wantsJson()) {

            return response()->json($response);
        }

        return redirect()->back()->with('message', $response['message']);

    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Group deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Group deleted.');
    }
}

resources/views/backend/groups/create.blade.php
@extends('backend.master')
@section('title') Groups @stop
@section('page-header') Self help group @stop
@section('page-header-desc') create a new self-help group @stop
@section('content')

    <div class="row gutter">
        <div class="col-md-12">
            <form class="panel" action="{{ route('groups.store') }}" method="post" autocomplete="off">
                {{ csrf_field() }}
                <div class="panel-body">
                    @include('backend.groups.form', [
                    'group' => new \App\Models\Group,
                    'user' => new \App\Models\User,
                    'action' => 'submit'
                    ])
                </div>

            </form>
        </div>
    </div>
@stop

@push('js')
    <script src="{{ asset('js/datatables/dataTables.min.js') }}"></script>
    <script src="{{ asset('js/datatables/dataTables.bootstrap.min.js') }}"></script>
@endpush

resources/views/backend/groups/edit.blade.php
@extends('backend.master')
@section('title') Groups @stop
@section('page-header') Self help groups @stop
@section('page-header-desc') edit self-help group @stop
@section('content')

    <div class="row gutter">
        <div class="col-md-12">
            <form class="panel" action="{{ route('groups.update', $group->id) }}" method="post" autocomplete="off">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="panel-body">
                    @include('backend.groups.form', [
                    'group' => $group,
                    'user' => $user,
                    'action' => 'update'
                    ])
                </div>

            </form>
        </div>
    </div>
@stop

@push('js')
    <script src="{{ asset('js/datatables/dataTables.min.js') }}"></script>
    <script src="{{ asset('js/datatables/dataTables.bootstrap.min.js') }}"></script>
@endpush

resources/views/backend/groups/form.blade.php
<div class="form-group has-feedback">
    <div class="row gutter">
        <div class="col-md-6">
            <label class="control-label">Group Name <span class="text-danger small">*</span></label>
            <input type="text"
                   class="form-control"
                   name="name"
                   required
                   value="{{ $group->name }}">
            @if($errors->has('name'))
                <i class="form-control-feedback"></i>
                <small class="help-block text-danger">{{ $errors->first('name') }}</small>
            @endif
        </div>
        <div class="col-md-6">
            <label class="control-label" for="email">Group's Email</label>
            <input type="email"
                   class="form-control"
                   name="email"
                   id="email"
                   placeholder="example@lamuwonesacco.or.ke"
                   required
                   value="{{ $group->email }}">
            @if($errors->has('email'))
                <i class="form-control-feedback"></i>
                <small class="help-block text-danger">{{ $errors->first('email') }}</small>
            @endif
        </div>
    </div>
</div>
<div class="form-group has-feedback">
    <div class="row gutter">

        <div class="col-md-6">
            <label class="control-label" for="telephone">Telephone</label>
            <input type="text"
                   class="form-control"
                   name="telephone"
                   id="telephone"
                   value="{{ $group->telephone }}"
                   required
                   placeholder="071 123 1233">
            @if($errors->has('telephone'))
                <i class="form-control-feedback"></i>
                <small class="help-block text-danger">{{ $errors->first('telephone') }}</small>
            @endif
        </div>
        <div class="col-md-6">
            <label class="control-label" for="location">Location</label>
            <input type="text"
                   class="form-control"
                   name="location"
                   id="location"
                   required
                   placeholder="group's physical location eg lamu ...."
                   value="{{ $group->location }}" >
            @if($errors->has('location'))
                <i class="form-control-feedback"></i>
                <small class="help-block text-danger"> {{ $errors->first('location') }}</small>
            @endif
        </div>
    </div>
</div>
<hr>
<hr>
<legend class="text-center text-success">Group Admin Account details</legend>
<div class="form-group has-feedback">
    <div class="row gutter">
        <div class="col-md-4">
            <label class="control-label" for="admin_name">Name <span class="text-danger small">*</span></label>
            <input type="name"
                   class="form-control"
                   name="admin_name"
                   id="admin_name"
                   value="{{ $user->name }}"
                   required
                   placeholder="Ali Mohamed">
            @if($errors->has('admin_name'))
                <i class="form-control-feedback"></i>
                <small class="help-block text-danger"> {{ $errors->first('admin_name') }}</small>
            @endif
        </div>
        <div class="col-md-4">
            <label class="control-label" for="admin_email">Email <span class="text-danger small">*</span> </label>
            <input type="email"
                   class="form-control"
                   name="admin_email"
                   id="admin_email"
                   value=" {{ $user->email }}"
                   required
                   placeholder="example@lamuwomensacco.or.ke">
            @if($errors->has('admin_email'))
                <i class="form-control-feedback"></i>
                <small class="help-block text-danger">{{ $errors->first('admin_email') }}</small>
            @endif
        </div>
        <div class="col-md-4">
            <label class="control-label" for="admin_telephone">Telephone </label>
            <input type="text"
                   class="form-control"
                   name="admin_telephone"
                   id="admin_telephone"
                   required
                   value="{{ $user->telephone }}"
                   placeholder="074 123 2344">
            @if($errors->has('admin_telephone'))
                <i class="form-control-feedback"></i>
                <small class="help-block text-danger">{{ $errors->first('admin_telephone') }}</small>
            @endif
        </div>
    </div>
</div>
<hr>
<button type="submit" class="btn btn-success">{{ $action }}</button>
<a type="submit" href="{{ route('groups.index') }}" class="btn btn-default pull-right">Cancel</a>
<hr>
<div class="form-group">
    <span class="text-danger small">*</span> <span class="text-center-sm">Required fields</span>
</div>

resources/views/backend/groups/index.blade.php
@extends('backend.master')
@section('title') Groups @stop
@section('page-header') Self help group @stop
@section('page-header-desc') details about the self help group @stop
@section('content')

    <div class="row gutter">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-body">
                    <div class="table">
                        <table class="table table-striped table-condensed table-bordered" id="table">
                            <thead>
                            <tr>
                                <th>name</th>
                                <th>location</th>
                                <th>telephone</th>
                                <th>contact Person</th>
                                <th>Members</th>
                                <th>Contribution (Ksh)</th>
                                <th>Action</th>
                            </tr>
                            </thead>

                        </table>
                    </div>

                </div>

            </div>
        </div>
    </div>
@stop

@push('js')
    <script src="{{ asset('js/datatables/dataTables.min.js') }}"></script>
    <script src="{{ asset('js/datatables/dataTables.bootstrap.min.js') }}"></script>
    @include('templates.datatable')

    <script>
        $(function () {
            $('#table').DataTable({
                ajax: $.fn.dataTable.pipeline({
                    url: '{!! route('groups.datatable') !!}',
                    pages: 5
                }),
                columns: [
                    {data: 'name', name: 'name'},
                    {data: 'location', name: 'location'},
                    {data: 'telephone', name: 'telephone'},
                    {data: 'user.name', name: 'user.name'},
                    {data: 'members_count', name: 'members_count'},
                    {data: 'contribution', name: 'contribution'},
                    // {data: 'roles', name: 'roles', orderable: false, searchable: false},
                    // {data: 'active', name: 'active'},
                    // {data: 'last_sign_in', name: 'last_sign_in'},
                    // {data: 'created_at', name: 'created_at'},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ]
            });
        });
    </script>

@endpush
@push('css')
    <link rel="stylesheet" href="{{ asset('css/datatables/dataTables.bs.min.css') }}">
@endpush