routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.master');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


/**
 * Backend Routes
 */

Route::group([
    'prefix' => 'intranet',
    'middleware' => 'auth'
], function () {

    Route::get('users/datatable', 'UsersController@dataTable')->name('users.datatable');
    Route::get('groups/datatable', 'GroupsController@dataTable')->name('groups.datatable');
    Route::get('members/datatable', 'MembersController@dataTable')->name('members.datatable');
    Route::get('contributions/datatable', 'ContributionsController@dataTable')->name('contributions.datatable');

    Route::resource('users', 'UsersController');
    Route::resource('members', 'MembersController');
    Route::resource('groups', 'GroupsController');
    Route::resource('contributions', 'ContributionsController');
});

resources/views/backend/master.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {{--<meta name="description" content="Arise Admin Dashboard" />--}}
    {{--<meta name="keywords" content="Admin, Dashboard, Bootstrap3, Sass, transform, CSS3, HTML5, Web design, UI Design, Responsive Dashboard, Responsive Admin, Admin Theme, Best Admin UI, Bootstrap Theme, Themeforest, Bootstrap, C3 Graphs, D3 Graphs, NVD3 Graphs, Admin Skin, Black Admin Dashboard, Grey Admin Dashboard, Dark Admin Dashboard, Simple Admin Dashboard, Simple Admin Theme, Simple Bootstrap Dashboard, Invoice, Tasks, Profile" />--}}

    <link rel="shortcut icon" href="{{ asset('img/fav.png') }}">
    <title>{{ str_replace('-', ' ', config('app.name')) }} - @yield('title')   </title>

    <!-- Bootstrap CSS -->
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet" media="screen"/>

    <!-- Main CSS -->
    <link href="{{ asset('css/main.css') }}" rel="stylesheet" media="screen"/>

    <!-- Ion Icons -->
    <link href="{{ asset('fonts/icomoon/icomoon.css') }}" rel="stylesheet"/>

@yield('css')
@stack('css')
<!-- HTML5 shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<!-- Header starts -->
<header>

    <!-- Logo starts -->
    <a href="{{ route('home') }}" class="logo">
        <img src="{{ asset('img/logo.png') }}" alt="Logo" width="50" height="50"/>
    </a>
    <!-- Logo ends -->

    <!-- Header actions starts -->
    <ul id="header-actions" class="clearfix">
        <li class="list-box hidden-xs dropdown">
            <a id="drop2" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-warning2"></i>
            </a>
            <span class="info-label blue-bg">5</span>
            <ul class="dropdown-menu imp-notify">
                <li class="dropdown-header">You have 3 notifications</li>
                <li>
                    <div class="icon">
                        <img src="img/thumbs/user10.png" alt="Arise Admin">
                    </div>
                    <div class="details">
                        <strong class="text-danger">Rogie King</strong>
                        <span>Firefox is a free, open-source web browser from Mozilla.</span>
                    </div>
                </li>
                <li>
                    <div class="icon">
                        <img src="img/thumbs/user6.png" alt="Arise Admin">
                    </div>
                    <div class="details">
                        <strong class="text-success">Dan Cederholm</strong>
                        <span>IE is a free web browser from Microsoft.</span>
                    </div>
                </li>
                <li>
                    <div class="icon">
                        <img src="img/thumbs/user1.png" alt="Arise Admin">
                    </div>
                    <div class="details">
                        <strong class="text-info">Justin Mezzell</strong>
                        <span>Safari is known for its sleek design and ease of use.</span>
                    </div>
                </li>
                <li class="dropdown-footer">See all the notifications</li>
            </ul>
        </li>
        <li class="list-box hidden-xs dropdown">
            <a id="drop3" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-archive2"></i>
            </a>
            <span class="info-label red-bg">3</span>
            <ul class="dropdown-menu progress-info">
                <li class="dropdown-header">You have 7 pending tasks</li>
                <li>
                    <div class="progress-info">
                        <strong class="text-danger">Critical</strong>
                        <span>New Dashboard Design</span>
                        <span class="pull-right text-danger">20%</span>
                    </div>
                    <div class="progress progress-md no-margin">
                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="20"
                             aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                            <span class="sr-only">20% Complete (success)</span>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="progress-info">
                        <strong class="text-info">Primary</strong>
                        <span>UI Changes in V2</span>
                        <span class="pull-right">90%</span>
                    </div>
                    <div class="progress progress-sm no-margin">
                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="90"
                             aria-valuemin="0" aria-valuemax="100" style="width: 90%">
                            <span class="sr-only">90% Complete</span>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="progress-info">
                        <strong class="text-warning">Urgent</strong>
                        <span>Bug Fix #123</span>
                        <span class="pull-right">60%</span>
                    </div>
                    <div class="progress progress-xs no-margin">
                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60"
                             aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                            <span class="sr-only">60% Complete (warning)</span>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="progress-info">
                        <span>Bug Fix #111</span>
                        <span class="pull-right text-success">Complete</span>
                    </div>
                    <div class="progress progress-xs no-margin">
                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100"
                             aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                            <span class="sr-only">100% Complete (warning)</span>
                        </div>
                    </div>
                </li>
                <li class="dropdown-footer">See all the tasks</li>
            </ul>
        </li>
        <li class="list-box user-admin hidden-xs dropdown">
            <div class="admin-details">
                <div class="name">Sean</div>
                <div class="designation">System Admin</div>
            </div>
            <a id="drop4" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-user"></i>
            </a>
            <ul class="dropdown-menu sm">
                <li class="dropdown-content">
                    <a href="profile.html">Edit Profile</a>
                    <a href="forgot-pwd.html">Change Password</a>
                    <a href="styled-inputs.html">Settings</a>
                    <a href="login.html">Logout</a>
                </li>
            </ul>
        </li>
        <li>
            <button type="button" id="toggleMenu" class="toggle-menu">
                <i class="collapse-menu-icon"></i>
            </button>
        </li>
    </ul>
    <!-- Header actions ends -->

    <div class="custom-search hidden-sm hidden-xs">
        <input type="text" class="search-query" placeholder="Search here ...">
        <i class="icon-search3"></i>
    </div>
</header>
<!-- Header ends -->

<!-- Left sidebar start -->
<div class="vertical-nav">

    <!-- Collapse menu starts -->
    <button class="collapse-menu">
        <i class="icon-menu2"></i>
    </button>
    <!-- Collapse menu ends -->

    <!-- Current user starts -->
    <div class="user-details clearfix">
        <a href="profile.html" class="user-img">
            <img src="{{ asset('img/thumbs/user1.png') }}" alt="User Info">
            <span class="likes-info">9</span>
        </a>
        <h5 class="user-name">Muhidin</h5>
    </div>
    <!-- Current user ends -->

    <!-- Sidebar menu start -->
    <ul class="menu clearfix">
        <li class="{{ Request::is('intranet/home') ? 'active selected' : '' }}">
            <a href="{{ route('home') }}">
                <i class="icon-air-play"></i>
                <span class="menu-item">Dashboard</span>
            </a>
        </li>
        <li class="{{ Request::is('intranet/groups*') ? 'active selected' : '' }}">
            <a href='{{ route('groups.index') }}'>
                <i class="icon-global"></i>
                <span class="menu-item">Groups</span>
            </a>
        </li>
        <li class="{{ Request::is('intranet/members*') ? 'active selected' : '' }}">
            <a href="{{ route('members.index') }}">
                <i class="icon-users"></i>
                <span class="menu-item">Members</span>
            </a>

        </li>
        <li class="{{ Request::is('intranet/loans*') ? 'active selected' : '' }}">
            <a href=''>
                <i class="icon-gift2"></i>
                <span class="menu-item">Loans</span>
            </a>
        </li>
        <li class="{{ Request::is('intranet/contributions*') ? 'active selected' : '' }}">
            <a href='{{ route('contributions.index') }}'>
                <i class="icon-share"></i>
                <span class="menu-item">Contributions</span>
            </a>
        </li>
        <li class="{{ Request::is('intranet/users') ? 'active selected' : '' }}">
            <a href='{{ route('users.index') }}'>
                <i class="icon-user-check"></i>
                <span class="menu-item">User Accounts</span>
            </a>
        </li>
        <li class="{{ Request::is('intranet/backups') ? 'active selected' : '' }}">
            <a href='calendar.html'>
                <i class="icon-server"></i>
                <span class="menu-item">Backup</span>
            </a>
        </li>
        <li>
            <a href=''>
                <i class="icon-gears"></i>
                <span class="menu-item">Settings</span>
            </a>
        </li>
        <li class="{{ Request::is('intranet/roles') ? 'active selected' : '' }}">
            <a href=''>
                <i class="icon-lock"></i>
                <span class="menu-item">Roles</span>
            </a>
        </li>
        <li>
            <a href=''>
                <i class="icon-key"></i>
                <span class="menu-item">Permissions</span>
            </a>
        </li>
    </ul>
    <!-- Sidebar menu snd -->
</div>
<!-- Left sidebar end -->

<!-- Dashboard Wrapper Start -->
<div class="dashboard-wrapper dashboard-wrapper-lg">

    <!-- Container fluid Starts -->
    <div class="container-fluid">

        <!-- Top Bar Starts -->
        <div class="top-bar clearfix">
            <div class="row gutter">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="page-title">

                        <h3>@yield('page-header')</h3>
                        <p>@yield('page-header-desc')</p>
                    </div>
                </div>
                @yield('page-action')
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="btn-group btn-group-sm pull-right">
                        <button data-toggle="dropdown" class="btn btn-default dropdown-toggle" type="button"
                                aria-expanded="false"><span class="circless animate"></span>Action
                            <span class="caret"></span></button>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="{{ route('groups.create') }}"> <i class="icon-world"></i> Add Group</a></li>
                            <li><a href="{{ route('members.create') }}"><i class="icon-users"></i> Add Member</a></li>
                            <li><a href="{{ route('contributions.store') }}"><i class="icon-share"></i> Add contribution</a></li>
                            </ul>
                    </div>
                </div>

            </div>
        </div>
        <!-- Top Bar Ends -->

        @yield('content')

    </div>
    <!-- Container fluid ends -->

</div>
<!-- Dashboard Wrapper End -->

<!-- Footer Start -->
<footer>
    Copyright {{ str_replace('-', ' ', config('app.name')) }} <span>2018</span>
</footer>
<!-- Footer end -->

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{{ asset('js/jquery.js') }}"></script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{{ asset('js/bootstrap.min.js') }}"></script>

<!-- jquery ScrollUp JS -->
<script src="{{ asset('js/scrollup/jquery.scrollUp.js') }}"></script>

<!-- Custom JS -->
<script src="{{ asset('js/custom.js') }}"></script>

@yield('js')
@stack('js')
</body>
</html>