routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.master');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


/**
 * Backend Routes
 */

Route::group([
    'prefix' => 'intranet',
    'middleware' => 'auth'
], function () {

    Route::get('users/datatable', 'UsersController@dataTable')->name('users.datatable');
    Route::get('groups/datatable', 'GroupsController@dataTable')->name('groups.datatable');
    Route::get('members/datatable', 'MembersController@dataTable')->name('members.datatable');
    Route::get('contributions/datatable', 'ContributionsController@dataTable')->name('contributions.datatable');

    Route::resource('users', 'UsersController');
    Route::resource('members', 'MembersController');
    Route::resource('groups', 'GroupsController');
    Route::resource('contributions', 'ContributionsController');
});

app/Models/Contribution.php
<?php

namespace App\Models;

use Spatie\Activitylog\LogsActivity;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Spatie\Activitylog\LogsActivityInterface;
use Venturecraft\Revisionable\RevisionableTrait;

/**
 * Class Contribution.
 *
 * @package namespace App\Models;
 */
class Contribution extends Model implements LogsActivityInterface
{
    use Sluggable, LogsActivity, RevisionableTrait;

    protected $revisionEnabled = true;
    protected $revisionCleanup = true; //Remove old revisions
    protected $historyLimit = 500; //Stop tracking revisions after 500 changes have been made.

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'member_id', 'amount', 'contribution_date', 'transaction_code', 'slug'
    ];

    /*
    |--------------------------------------------------------------------------
    | FUNCTIONS
    |--------------------------------------------------------------------------
    */

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'amount'
            ]
        ];
    }

    /**
     * Get the message that needs to be logged for the given event name.
     *
     * @param string $eventName
     *
     * @return string
     */
    public function getActivityDescriptionForEvent($eventName)
    {
        if ($eventName == 'created') {
            return 'Contribution "' . $this->slug . '" was created';
        }

        if ($eventName == 'updated') {
            return 'Contribution "' . $this->slug . '" was updated';
        }

        if ($eventName == 'deleted') {
            return 'Contribution "' . $this->slug . '" was deleted';
        }

        return '';
    }

    /*
   |--------------------------------------------------------------------------
   | RELATIONSHIPS
   |--------------------------------------------------------------------------
   */

    /**
     * Contribution belongs to a member
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function member()
    {
        return $this->belongsTo(Member::class, 'member_id');
    }

}

app/Http/Controllers/ContributionsController.php
<?php

namespace App\Http\Controllers;

use App\Contracts\Repositories\ContributionRepository;
use App\Contracts\Repositories\MemberRepository;
use App\Http\Requests\ContributionCreateRequest;
use App\Http\Requests\ContributionUpdateRequest;
use App\Validators\ContributionValidator;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;

/**
 * Class ContributionsController.
 *
 * @package namespace App\Http\Controllers;
 */
class ContributionsController extends Controller
{
    /**
     * @var ContributionRepository
     */
    protected $repository;

    /**
     * @var MemberRepository
     */
    protected $memberRepository;

    /**
     * ContributionsController constructor.
     *
     * @param ContributionRepository $repository
     * @param MemberRepository $memberRepository
     */
    public function __construct(ContributionRepository $repository, MemberRepository $memberRepository)
    {
        $this->repository = $repository;
        $this->memberRepository = $memberRepository;
    }

    public function dataTable()
    {
        return $this->repository->getDataTable();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $contributions = $this->repository->all();

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $contributions,
            ]);
        }

        return view('backend.contributions.index', compact('contributions'));
    }

    public function create()
    {
        $members = $this->memberRepository->skipPresenter()->all();

        return view('backend.contributions.create', compact('members'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  ContributionCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     *
     */
    public function store(ContributionCreateRequest $request)
    {
        $this->repository->create($request->all());

        session()->flash('message', 'contribution created.');

        return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $contribution = $this->repository->find($id);

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $contribution,
            ]);
        }

        return view('contributions.show', compact('contribution'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $contribution = $this->repository->skipPresenter()->find($id);

        return view('contributions.edit', compact('contribution'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  ContributionUpdateRequest $request
     * @param  string $id
     *
     * @return Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function update(ContributionUpdateRequest $request, $id)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_UPDATE);

            $contribution = $this->repository->update($request->all(), $id);

            $response = [
                'message' => 'Contribution updated.',
                'data'    => $contribution->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Contribution deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Contribution deleted.');
    }
}

resources/views/backend/contributions/create.blade.php
@extends('backend.master')
@section('title') Contributions @stop
@section('page-header') Contributions @stop
@section('page-header-desc') create new contribution details @stop
@section('content')
    <div class="row gutter">
        <div class="col-md-12">
            @if(session()->has('message'))
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <i class="icon-check2"></i><strong>{{ session()->get('message') }}</strong>
                </div>
            @endif
            <form class="panel" action="{{ route('contributions.store') }}" method="post" autocomplete="off">
                {{ csrf_field() }}
                <div class="panel-body">
                    @include('backend.contributions.form', [
                    'contribution' => new \App\Models\Contribution,
                    'action' => 'submit'
                    ])
                </div>

            </form>
        </div>
    </div>
@stop

@push('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="{{ asset('js/datatables/dataTables.min.js') }}"></script>
    <script src="{{ asset('js/datatables/dataTables.bootstrap.min.js') }}"></script>

    <script>
        $('select').select2()
    </script>
@endpush

@push('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />

@endpush

resources/views/backend/contributions/edit.blade.php
@extends('backend.master')
@section('title') Contributions @stop
@section('page-header') Contributions @stop
@section('page-header-desc') update contribution details @stop
@section('content')
    <div class="row gutter">
        <div class="col-md-12">
            @if(session()->has('success'))
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <i class="icon-check2"></i><strong>{{ session()->get('success') }}</strong>
                </div>
            @endif
            <form class="panel" action="{{ route('contributions.update', $contribution->id) }}" method="post"
                  autocomplete="off">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="panel-body">
                    @include('backend.contributions.form', [
                    'contribution' => $contribution,
                    'action' => 'update'
                    ])
                </div>

            </form>
        </div>
    </div>
@stop

@push('js')
    <script src="{{ asset('js/datatables/dataTables.min.js') }}"></script>
    <script src="{{ asset('js/datatables/dataTables.bootstrap.min.js') }}"></script>
@endpush

resources/views/backend/contributions/form.blade.php
<div class="form-group has-feedback">
    <div class="row gutter">
        <div class="col-md-4">
            <label class="control-label" for="contribution_date">Transaction date <span
                        class="text-danger small">*</span></label>
            <input type="date"
                   class="form-control"
                   required
                   name="contribution_date"
                   id="contribution_date">
            @if($errors->has('contribution_date'))
                <i class="form-control-feedback"></i>
                <small class="help-block text-danger">{{ $errors->first('contribution_date') }}</small>
            @endif
        </div>
        <div class="col-md-4">
            <label class="control-label" for="control">Transaction Code </label>
            <input type="text"
                   class="form-control"
                   name="transaction_code"
                   id="control"
                   placeholder="Transaction code for the contribution"
                   value="{{ $contribution->transaction_code }}">
            @if($errors->has('transaction_code'))
                <i class="form-control-feedback"></i>
                <small class="help-block text-danger">{{ $errors->first('transaction_code') }}</small>
            @endif
        </div>
        <div class="col-md-4">
            <label class="control-label" for="amount">Amount <span class="text-danger small">*</span></label>
            <input type="number"
                   class="form-control"
                   name="amount"
                   id="amount"
                   required
                   placeholder="Amount contributed in numeric eg 3400"
                   value="{{ $contribution->amount }}">
            @if($errors->has('amount'))
                <i class="form-control-feedback"></i>
                <small class="help-block text-danger">{{ $errors->first('amount') }}</small>
            @endif
        </div>
    </div>
</div>

<div class="form-group has-feedback">
    <div class="row gutter">
        <div class="col-md-4">
            <label class="control-label" for="member_id">Member</label>
            <select class="form-control" id="member_id" name="member_id">
                @foreach($members as $member)
                    <option value="{{ $member->id }}">{{ $member->name }}</option>
                @endforeach
            </select>
            @if($errors->has('member_id'))
                <i class="form-control-feedback"></i>
                <small class="help-block text-danger">{{ $errors->first('member_id') }}</small>
            @endif
        </div>

    </div>
</div>
<button type="submit" class="btn btn-success">{{ $action }}</button>
<a type="submit" href="{{ route('contributions.index') }}" class="btn btn-default pull-right">Cancel</a>
<hr>
<div class="form-group">
    <span class="text-danger small">*</span> <span class="text-center-sm">Required fields</span>
</div>

resources/views/backend/contributions/index.blade.php
@extends('backend.master')
@section('title') Contributions @stop
@section('page-header') Contributions @stop
@section('page-header-desc') details about member contributions @stop
@section('content')

    <div class="row gutter">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-body">
                    <div class="table">
                        <table class="table table-striped table-condensed table-bordered" id="table">
                            <thead>
                            <tr>
                                <th>Amount</th>
                                <th>Transaction Code</th>
                                <th>Date</th>
                                <th>Member name</th>
                                <th>Action</th>
                            </tr>
                            </thead>

                        </table>
                    </div>

                </div>

            </div>
        </div>
    </div>
@stop

@push('js')
    <script src="{{ asset('js/datatables/dataTables.min.js') }}"></script>
    <script src="{{ asset('js/datatables/dataTables.bootstrap.min.js') }}"></script>
    @include('templates.datatable')

    <script>
        $(function () {
            $('#table').DataTable({
                ajax: $.fn.dataTable.pipeline({
                    url: '{!! route('contributions.datatable') !!}',
                    pages: 5
                }),
                columns: [
                    {data: 'amount', name: 'amount'},
                    {data: 'transaction_code', name: 'transaction_code'},
                    {data: 'contribution_date', name: 'contribution_date'},
                    {data: 'member.name', name: 'member.name'},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ]
            });
        });
    </script>

@endpush
@push('css')
    <link rel="stylesheet" href="{{ asset('css/datatables/dataTables.bs.min.css') }}">
@endpush