routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.master');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


/**
 * Backend Routes
 */

Route::group([
    'prefix' => 'intranet',
    'middleware' => 'auth'
], function () {

    Route::get('users/datatable', 'UsersController@dataTable')->name('users.datatable');
    Route::get('groups/datatable', 'GroupsController@dataTable')->name('groups.datatable');
    Route::get('members/datatable', 'MembersController@dataTable')->name('members.datatable');
    Route::get('contributions/datatable', 'ContributionsController@dataTable')->name('contributions.datatable');

    Route::resource('users', 'UsersController');
    Route::resource('members', 'MembersController');
    Route::resource('groups', 'GroupsController');
    Route::resource('contributions', 'ContributionsController');
});

app/Models/Member.php
<?php

namespace App\Models;

use Spatie\Activitylog\LogsActivity;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\LogsActivityInterface;
use Venturecraft\Revisionable\RevisionableTrait;

/**
 * Class Member.
 *
 * @package namespace App\Models;
 */
class Member extends Model implements LogsActivityInterface
{
    use Sluggable, LogsActivity, SoftDeletes, RevisionableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'telephone', 'membershipNo', 'slug', 'nationalID', 'group_id'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    protected $revisionEnabled = true;
    protected $revisionCleanup = true; //Remove old revisions
    protected $historyLimit = 500; //Stop tracking revisions after 500 changes have been made.

    /*
    |--------------------------------------------------------------------------
    | FUNCTIONS
    |--------------------------------------------------------------------------
    */

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    /**
     * Get the message that needs to be logged for the given event name.
     *
     * @param string $eventName
     *
     * @return string
     */
    public function getActivityDescriptionForEvent($eventName)
    {
        if ($eventName == 'created') {
            return 'Member "' . $this->name . '" was created';
        }

        if ($eventName == 'updated') {
            return 'Member "' . $this->name . '" was updated';
        }

        if ($eventName == 'deleted') {
            return 'Member "' . $this->name . '" was deleted';
        }

        return '';
    }

    /**
     * @return Member|\Illuminate\Database\Query\Builder
     */
    public function memberContribution()
    {
        return $this->leftJoin('contributions', 'contributions.member_id', '=', 'member.id');
    }

    /*
   |--------------------------------------------------------------------------
   | RELATIONSHIPS
   |--------------------------------------------------------------------------
   */

    /**
     * A member can make many contributions
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function contribution()
    {
        return $this->hasMany(Contribution::class);
    }

    /**
     *  A member belongs to a group
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function group()
    {
        return $this->belongsTo(Group::class, 'group_id');
    }
}

app/Http/Controllers/MembersController.php
<?php

namespace App\Http\Controllers;

use App\Contracts\Repositories\MemberRepository;
use App\Http\Requests\MemberCreateRequest;
use App\Http\Requests\MemberUpdateRequest;
use Illuminate\Support\Facades\Auth;

/**
 * Class MembersController.
 *
 * @package namespace App\Http\Controllers;
 */
class MembersController extends Controller
{
    /**
     * @var MemberRepository
     */
    protected $repository;

    /**
     * MembersController constructor.
     *
     * @param MemberRepository $repository
     */
    public function __construct(MemberRepository $repository)
    {
        $this->repository = $repository;
    }

    public function dataTable()
    {
        return $this->repository->getDataTable();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $members = $this->repository->all();

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $members,
            ]);
        }

        return view('backend.members.index', compact('members'));
    }

    /**
     * Shows the form for creating a new resource
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('backend.members.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  MemberCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(MemberCreateRequest $request)
    {
        $this->repository->create([
            'group_id'     => Auth::user()->group ? Auth::user()->group->id : null,
            'name'         => $request->name,
            'email'        => $request->email,
            'membershipNo' => $request->membershipNo,
            'telephone'    => $request->telephone,
            'nationalID'   => $request->nationalID,
        ]);

        session()->flash('success', 'Member created.');
        $response = [
            'message' => 'Member created.',
        ];

        if ($request->wantsJson()) {

            return response()->json($response);
        }

        return redirect()->back()->with('message', $response['message']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $member = $this->repository->find($id);

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $member,
            ]);
        }

        return view('members.show', compact('member'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $member = $this->repository->skipPresenter()->find($id);

        return view('backend.members.edit', compact('member'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  MemberUpdateRequest $request
     * @param  string $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(MemberUpdateRequest $request, $id)
    {
        $this->repository->update([
            'name'         => $request->name,
            'email'        => $request->email,
            'membershipNo' => $request->membershipNo,
            'telephone'    => $request->telephone,
            'nationalID'   => $request->nationalID,
        ], $id);

        session()->flash('success', 'Member updated.');

        return redirect()->back();

    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Member deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Member deleted.');
    }
}

resources/views/backend/members/create.blade.php
@extends('backend.master')
@section('title') Members @stop
@section('page-header') Members @stop
@section('page-header-desc') create new member @stop
@section('content')
    <div class="row gutter">
        <div class="col-md-12">
            @if(session()->has('message'))
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <i class="icon-check2"></i><strong>{{ session()->get('message') }}</strong>
                </div>
            @endif
            <form class="panel" action="{{ route('members.store') }}" method="post" autocomplete="off">
                {{ csrf_field() }}
                <div class="panel-body">
                    @include('backend.members.form', [
                    'member' => new \App\Models\Member,
                    'action' => 'submit'
                    ])
                </div>

            </form>
        </div>
    </div>
@stop

@push('js')
    <script src="{{ asset('js/datatables/dataTables.min.js') }}"></script>
    <script src="{{ asset('js/datatables/dataTables.bootstrap.min.js') }}"></script>
@endpush

resources/views/backend/members/edit.blade.php
@extends('backend.master')
@section('title') Members @stop
@section('page-header') Members @stop
@section('page-header-desc') update member details @stop
@section('content')
    <div class="row gutter">
        <div class="col-md-12">
            @if(session()->has('success'))
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <i class="icon-check2"></i><strong>{{ session()->get('success') }}</strong>
                </div>
            @endif
            <form class="panel" action="{{ route('members.update', $member->id) }}" method="post" autocomplete="off">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="panel-body">
                    @include('backend.members.form', [
                    'member' => $member,
                    'action' => 'update'
                    ])
                </div>

            </form>
        </div>
    </div>
@stop

@push('js')
    <script src="{{ asset('js/datatables/dataTables.min.js') }}"></script>
    <script src="{{ asset('js/datatables/dataTables.bootstrap.min.js') }}"></script>
@endpush

resources/views/backend/members/form.blade.php
<div class="form-group has-feedback">
    <div class="row gutter">
        <div class="col-md-6">
            <label class="control-label">Full Name <span class="text-danger small">*</span></label>
            <input type="text"
                   class="form-control"
                   name="name"
                   placeholder="Ahmed Ali Hashim"
                   required
                   value="{{ $member->name }}">
            @if($errors->has('name'))
                <i class="form-control-feedback"></i>
                <small class="help-block text-danger">{{ $errors->first('name') }}</small>
            @endif
        </div>
        <div class="col-md-6">
            <label class="control-label" for="email">Email</label>
            <input type="email"
                   class="form-control"
                   name="email"
                   id="email"
                   placeholder="example@lamuwonesacco.or.ke"
                   value="{{ $member->email }}">
            @if($errors->has('email'))
                <i class="form-control-feedback"></i>
                <small class="help-block text-danger">{{ $errors->first('email') }}</small>
            @endif
        </div>
    </div>
</div>
<div class="form-group has-feedback">
    <div class="row gutter">

        <div class="col-md-6">
            <label class="control-label" for="telephone">Telephone <span class="text-danger small">*</span></label>
            <input type="text"
                   class="form-control"
                   name="telephone"
                   id="telephone"
                   value="{{ $member->telephone }}"
                   required
                   placeholder="0711231233">
            @if($errors->has('telephone'))
                <i class="form-control-feedback"></i>
                <small class="help-block text-danger">{{ $errors->first('telephone') }}</small>
            @endif
        </div>
        <div class="col-md-6">
            <label class="control-label" for="nationalID">National identification number <span class="text-danger small">*</span></label>
            <input type="text"
                   class="form-control"
                   name="nationalID"
                   id="nationalID"
                   required
                   placeholder="ID number... 32324565"
                   value="{{ $member->nationalID }}" >
            @if($errors->has('nationalID'))
                <i class="form-control-feedback"></i>
                <small class="help-block text-danger"> {{ $errors->first('nationalID') }}</small>
            @endif
        </div>
    </div>
</div>

<div class="form-group has-feedback">
    <div class="row gutter">

        <div class="col-md-6">
            <label class="control-label" for="telephone">Membership Number </label>
            <input type="text"
                   class="form-control"
                   name="membershipNo"
                   id="membershipNo"
                   value="{{ $member->membershipNo }}"
                   required
                   placeholder="membership number">
            @if($errors->has('membershipNo'))
                <i class="form-control-feedback"></i>
                <small class="help-block text-danger">{{ $errors->first('membershipNo') }}</small>
            @endif
        </div>

    </div>
</div>

<button type="submit" class="btn btn-success">{{ $action }}</button>
<a type="submit" href="{{ route('members.index') }}" class="btn btn-default pull-right">Cancel</a>
<hr>
<div class="form-group">
    <span class="text-danger small">*</span> <span class="text-center-sm">Required fields</span>
</div>

resources/views/backend/members/index.blade.php
@extends('backend.master')
@section('title') Members @stop
@section('page-header') Members @stop
@section('page-header-desc') details about registered members @stop
@section('content')

    <div class="row gutter">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-condensed table-bordered no-margin" id="table">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>membershipNo</th>
                                <th>email</th>
                                <th>telephone</th>
                                <th>Identification No</th>
                                <th>Contribution (Ksh)</th>
                                <th>Action</th>
                            </tr>
                            </thead>

                        </table>
                    </div>

                </div>

            </div>
        </div>
    </div>
@stop

@push('js')
    <script src="{{ asset('js/datatables/dataTables.min.js') }}"></script>
    <script src="{{ asset('js/datatables/dataTables.bootstrap.min.js') }}"></script>
    @include('templates.datatable')

    <script>
        $(function () {
            $('#table').DataTable({
                ajax: $.fn.dataTable.pipeline({
                    url: '{!! route('members.datatable') !!}',
                    pages: 5
                }),
                columns: [
                    {data: 'name', name: 'name'},
                    {data: 'membershipNo', name: 'membershipNo'},
                    {data: 'email', name: 'email'},
                    {data: 'telephone', name: 'telephone'},
                    {data: 'nationalID', name: 'nationalID', orderable: false, searchable: false},
                    {data: 'contribution', name: 'contribution'},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ]
            });
        });
    </script>

@endpush
@push('css')
    <link rel="stylesheet" href="{{ asset('css/datatables/dataTables.bs.min.css') }}">
@endpush